import type { InvoiceData } from './buildInvoice';
import { customerMarkCode } from '../../shared/customerMark';

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function money(amount: number, currency: string): string {
  const n = Number.isFinite(amount) ? amount : 0;
  const formatted = Number.isInteger(n) ? String(n) : n.toFixed(2);
  return `${currency} ${formatted}`;
}

/** HTML invoice for PDF generation. */
export function buildInvoiceHtml(data: InvoiceData): string {
  const { business, customer, order, payments, currency } = data;
  const shop = escapeHtml(business?.name?.trim() || 'MyDarzi');
  const rows = order.items
    .map(
      item => `
      <tr>
        <td>${escapeHtml(item.garmentName)}</td>
        <td style="text-align:center">${item.quantity}</td>
        <td style="text-align:right">${escapeHtml(money(item.unitPrice, currency))}</td>
        <td style="text-align:right">${escapeHtml(money(item.lineTotal, currency))}</td>
      </tr>`,
    )
    .join('');

  const paymentRows = payments
    .map(p => {
      const date = p.paidAt.slice(0, 10);
      return `<li>${escapeHtml(money(p.amount, currency))} — ${escapeHtml(p.method)} (${escapeHtml(date)})</li>`;
    })
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: Arial, Helvetica, sans-serif; color: #1a1a1a; padding: 24px; font-size: 13px; }
    h1 { font-size: 22px; margin: 0 0 4px; color: #0f766e; }
    .muted { color: #64748b; margin: 2px 0; }
    .meta { margin: 16px 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th, td { border-bottom: 1px solid #e2e8f0; padding: 8px 4px; text-align: left; }
    th { color: #64748b; font-size: 11px; text-transform: uppercase; }
    .totals { margin-top: 16px; }
    .totals div { display: flex; justify-content: space-between; padding: 4px 0; }
    .strong { font-weight: 700; font-size: 15px; }
    .footer { margin-top: 24px; color: #64748b; font-size: 12px; }
  </style>
</head>
<body>
  <h1>${shop}</h1>
  ${business?.phone ? `<p class="muted">${escapeHtml(business.phone)}</p>` : ''}
  ${business?.address ? `<p class="muted">${escapeHtml(business.address)}</p>` : ''}
  <div class="meta">
    <div><strong>Invoice / Order:</strong> ${escapeHtml(order.orderNumber)}</div>
    ${customer ? `<div><strong>Fabric mark:</strong> #${escapeHtml(customerMarkCode(customer.id))}</div>` : ''}
    ${order.dueDate ? `<div><strong>Due:</strong> ${escapeHtml(order.dueDate)}</div>` : ''}
    ${customer ? `<div><strong>Customer:</strong> ${escapeHtml(customer.name)}</div>` : ''}
    ${customer?.phone || customer?.whatsapp ? `<div><strong>Phone:</strong> ${escapeHtml(customer.whatsapp || customer.phone || '')}</div>` : ''}
  </div>
  <table>
    <thead>
      <tr><th>Item</th><th style="text-align:center">Qty</th><th style="text-align:right">Price</th><th style="text-align:right">Total</th></tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="totals">
    ${order.discount > 0 ? `<div><span>Subtotal</span><span>${escapeHtml(money(order.subtotal, currency))}</span></div>` : ''}
    ${order.discount > 0 ? `<div><span>Discount</span><span>${escapeHtml(money(order.discount, currency))}</span></div>` : ''}
    <div class="strong"><span>Total</span><span>${escapeHtml(money(order.total, currency))}</span></div>
    <div><span>Paid</span><span>${escapeHtml(money(order.amountPaid ?? 0, currency))}</span></div>
    <div class="strong"><span>Balance</span><span>${escapeHtml(money(order.balance ?? 0, currency))}</span></div>
  </div>
  ${order.fabricInfo ? `<p><strong>Fabric:</strong> ${escapeHtml(order.fabricInfo)}</p>` : ''}
  ${order.color ? `<p><strong>Color:</strong> ${escapeHtml(order.color)}</p>` : ''}
  ${payments.length ? `<div><strong>Payments</strong><ul>${paymentRows}</ul></div>` : ''}
  <p class="footer">Thank you for your order. Generated by MyDarzi.</p>
</body>
</html>`;
}
